/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LectureRouteImport } from './routes/lecture'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as SourateNumRouteImport } from './routes/sourate.$num'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LectureRoute = LectureRouteImport.update({
  id: '/lecture',
  path: '/lecture',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const SourateNumRoute = SourateNumRouteImport.update({
  id: '/sourate/$num',
  path: '/sourate/$num',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lecture': typeof LectureRoute
  '/quiz': typeof QuizRoute
  '/sourate/$num': typeof SourateNumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lecture': typeof LectureRoute
  '/quiz': typeof QuizRoute
  '/sourate/$num': typeof SourateNumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lecture': typeof LectureRoute
  '/quiz': typeof QuizRoute
  '/sourate/$num': typeof SourateNumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lecture' | '/quiz' | '/sourate/$num'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lecture' | '/quiz' | '/sourate/$num'
  id: '__root__' | '/' | '/lecture' | '/quiz' | '/sourate/$num'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LectureRoute: typeof LectureRoute
  QuizRoute: typeof QuizRoute
  SourateNumRoute: typeof SourateNumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecture': {
      id: '/lecture'
      path: '/lecture'
      fullPath: '/lecture'
      preLoaderRoute: typeof LectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sourate/$num': {
      id: '/sourate/$num'
      path: '/sourate/$num'
      fullPath: '/sourate/$num'
      preLoaderRoute: typeof SourateNumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LectureRoute: LectureRoute,
  QuizRoute: QuizRoute,
  SourateNumRoute: SourateNumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
